name: Build SDL3 Image Libraries

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm64
            cmake-arch: arm64
            vcpkg-triplet: arm64-osx

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        repository: "HexaEngine/cimgui_impl"
        path: "cimgui"
        submodules: true

    - uses: actions/checkout@v4.1.7
      with:
        repository: 'libsdl-org/SDL'
        ref: 'release-3.2.10'
        path: 'cimgui/SDL'
        submodules: true

    - name: Install Dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install libpng jpeg libtiff webp libavif glfw glew glm

    - name: Prepare Vulkan SDK
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.3.204.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
        vulkan-use-cache: false

    - name: Configure SDL with CMake for macOS
      if: matrix.os == 'macos-latest'
      run: |
       cd cimgui/SDL
       cmake -S . -B ./build -DCMAKE_OSX_ARCHITECTURES=${{ matrix.cmake-arch }} -DCMAKE_BUILD_TYPE=Release -DSDL_STATIC=OFF -DSDL_SHARED=ON -DSDL_TEST=OFF

    - name: Build SDL3
      run: |
       cd cimgui/SDL
       cmake --build ./build --config Release
       cmake --install ./build --config Release --prefix install

    - name: Configure cimgui_impl with CMake for macOS
      if: matrix.os == 'macos-latest' || matrix.os == 'macos-13'
      run: |
        cd cimgui
        cmake -S ./ -B ./build -DCMAKE_OSX_ARCHITECTURES=${{ matrix.cmake-arch }} -DBACKENDS_SDL3_ONLY=ON -DIMGUI_WCHAR32=ON -DCMAKE_PREFIX_PATH="./SDL/install"

    - name: Build cimgui_impl
      run: |
        cd cimgui
        cmake --build ./build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: cimgui_impl-${{ matrix.os }}-${{ matrix.arch }}-artifacts
        path: |
            cimgui_impl/build/*.dll
            cimgui_impl/build/*.so
            cimgui_impl/build/*.dylib
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'